# docker-compose.yml 
# docker-compose file example for oxidized that will start along with docker daemon
oxidized:
  restart: always
#  image: oxidized/oxidized:latest 
  image: docker.eternalnet.ch/oxidized
  #build: ./
  ports:
    - 8888:8888/tcp
  environment:
    CONFIG_RELOAD_INTERVAL: 600
  volumes:
    - /etc/oxidized:/root/.config/oxidized 
    - /home/eternalnet/.ssh:/root/.ssh
#    - /var/www/CONFIG:/root/edoc
    - /var/lib/oxidized/:/var/lib/oxidized/

